# Numpy ndarray basics


In [1]:
#creating rank1 and rank2 elements using basic indexing by using built-in function to quickly and easily create ndarrays
import numpy as np
an_array = np.array([23,369,33664]) #create a rank1 array
print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
# test shape of the array we just created
print(an_array.shape)

(3,)


In [3]:
#becoz this is an 1 rank array we need only one index to access each element
print(an_array[0],an_array[1],an_array[2])

23 369 33664


In [4]:
an_array[0] = 2587
print (an_array)

[ 2587   369 33664]


# How to create rank 2 numpy array
A rank 2 array is one with two dimensions


In [5]:
a = np.array([[12,236,2345],[25,698,4569]]) #create rank 2 array
print(a) #print an array

print("This shape is 2 rows, 3 columns: ",a.shape) #rows * columns


[[  12  236 2345]
 [  25  698 4569]]
This shape is 2 rows, 3 columns:  (2, 3)


In [6]:
import numpy as np
# create a 2*2 array of zeros
exp = np.zeros((2,2))
print (exp)

[[0. 0.]
 [0. 0.]]


In [7]:
import numpy as np
# create a 2*2 array filled with 9.0
exp = np.full((2,2),(9.0))
print (exp)

[[9. 9.]
 [9. 9.]]


In [8]:
import numpy as np
# create a 2*2 matrix with diagonal 1s and the other 0
exp = np.eye(2,2)
print (exp)

[[1. 0.]
 [0. 1.]]


In [9]:
import numpy as np
# create a array of ones
exp1 = np.ones((1,2))
print (exp)

[[1. 0.]
 [0. 1.]]


In [10]:
print (exp1.shape)
print ()
print (exp1[0,1])

(1, 2)

1.0


In [11]:
# create random numbers
exp2 = np.random.random((2,2))
print(exp2)

[[0.91943503 0.9662021 ]
 [0.68563639 0.46994788]]


# ndarray indexing

In [12]:
#slice indexing
import numpy as np
an_array = np.array([[12,256,369],[14,278,23665],[12,366,9587]])
print(an_array)

[[   12   256   369]
 [   14   278 23665]
 [   12   366  9587]]


In [13]:
a_slice = an_array[:2,1:3]
print(a_slice)

[[  256   369]
 [  278 23665]]


In [14]:
a_slice = np.array(an_array[:2, 1:3]) 
print(a_slice)

[[  256   369]
 [  278 23665]]


In [17]:
row_rank2 = an_array[1:2, :]
print (row_rank2,row_rank2.shape)

[[   14   278 23665]] (1, 3)


In [18]:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print (col_rank1,col_rank1.shape)
print()
print (col_rank2,col_rank2.shape)



[256 278 366] (3,)

[[256]
 [278]
 [366]] (3, 1)


# Array indexing for changing elements

In [19]:
an_array = np.array([[25,236,236],[236,369,3364],[2366,4869,6321]])
print("original array:")
print(an_array)

original array:
[[  25  236  236]
 [ 236  369 3364]
 [2366 4869 6321]]


In [20]:
col_indices = np.array([0,1,2,0])
print('\ncol indices picked :',col_indices)

row_indices = np.arange(4)
print('\nRow indices picked :',row_indices)


col indices picked : [0 1 2 0]

Row indices picked : [0 1 2 3]


In [21]:
#examine pair indices of row_indices and col_indices
for row,col in zip(row_indices,col_indices):
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


# nd array boolen indexing
## array indexing for changing element

In [22]:
an_array = np.array([[26,36],[69,84],[97,53]])
print(an_array)

[[26 36]
 [69 84]
 [97 53]]


In [23]:
filter = (an_array>15)
filter

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [24]:
print(an_array[filter])

[26 36 69 84 97 53]


In [25]:
an_array[an_array>15]

array([26, 36, 69, 84, 97, 53])

In [26]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[126 136]
 [ 69 184]
 [ 97  53]]


# nd array data type and operations
## Data types

In [27]:
a = np.array([26,69])
print(a.dtype)

int64


In [28]:
a = np.array([26.3,69.69])
print(a.dtype)

float64


In [29]:
a = np.array([26.3,69.69], dtype =np.int64)
print(a.dtype)
print()
print(a)

int64

[26 69]


# Arithmatic array operations

In [30]:
a = np.array([[153,698],[897,632]],dtype=np.int64)
b = np.array([[236.33,586.321],[896.366,854.1266]],dtype=np.float64)
print(a)
print()
print(b)

[[153 698]
 [897 632]]

[[236.33   586.321 ]
 [896.366  854.1266]]


In [31]:
print(a+b)
print()
print(np.add(a,b))

[[ 389.33   1284.321 ]
 [1793.366  1486.1266]]

[[ 389.33   1284.321 ]
 [1793.366  1486.1266]]


# Like the above process we can do ("-",*,"/") and sqaure root also


In [32]:
#sqaure root
print(np.sqrt(a))

[[12.36931688 26.41968963]
 [29.94995826 25.13961018]]


In [33]:
#exponent(e**x)
print(np.exp(a))

[[2.79934052e+066 1.37261382e+303]
 [            inf 2.97928852e+274]]


/home/prakash/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


# statistical methods, Sorting, and Set Operations :


In [34]:
arr = 10 * np.random.randn(3,5)
print(arr)

[[ 3.1267841  -0.07646993 -5.88174823 -0.77611644  5.83221345]
 [ 2.87197243  0.94917023 -9.40042259  7.23505013 -0.92930927]
 [ 5.63602696 -4.33155691  0.43685448 12.27989731  4.50806159]]


In [35]:
#computing the off all elements
print(arr.mean())

1.432027153374168


In [36]:
#computing the mean by row
print(arr.mean(axis=1))

[0.44493259 0.14529219 3.70585669]


In [37]:
#computing the mean by column
print(arr.mean(axis=0))

[ 3.87826116 -1.15295221 -4.94843878  6.246277    3.13698859]


In [38]:
#computing sum of all the elements
print(arr.sum())

21.48040730061252


# sorting

In [39]:
unsorted = np.random.randn(20)
print(unsorted)

[ 0.66469398  0.65322391  0.588459    1.63536241 -0.1540327  -0.09123942
 -1.05897629 -0.05748362 -1.12491104  0.31928659  0.55464981  1.31563927
  0.47422641 -1.56924761 -0.26990377  0.29821484 -0.97093883  1.55205515
 -0.82759337 -0.39873378]


In [40]:
sorted=np.array(unsorted)
sorted.sort()
print (sorted)
print ()
print (unsorted)

[-1.56924761 -1.12491104 -1.05897629 -0.97093883 -0.82759337 -0.39873378
 -0.26990377 -0.1540327  -0.09123942 -0.05748362  0.29821484  0.31928659
  0.47422641  0.55464981  0.588459    0.65322391  0.66469398  1.31563927
  1.55205515  1.63536241]

[ 0.66469398  0.65322391  0.588459    1.63536241 -0.1540327  -0.09123942
 -1.05897629 -0.05748362 -1.12491104  0.31928659  0.55464981  1.31563927
  0.47422641 -1.56924761 -0.26990377  0.29821484 -0.97093883  1.55205515
 -0.82759337 -0.39873378]


In [41]:
unsorted.sort()
print(unsorted)

[-1.56924761 -1.12491104 -1.05897629 -0.97093883 -0.82759337 -0.39873378
 -0.26990377 -0.1540327  -0.09123942 -0.05748362  0.29821484  0.31928659
  0.47422641  0.55464981  0.588459    0.65322391  0.66469398  1.31563927
  1.55205515  1.63536241]


# FINDING UNIQUE ELEMENTS

In [42]:
array=np.array([1,2,4,1,2,4,6,35,4])
print(np.unique(array))

[ 1  2  4  6 35]


# Set operations with np.array data type:

In [43]:
a=np.array(['laptop','book','pen'])
b=np.array(['pen','laptop','chair'])
print(a,b)

['laptop' 'book' 'pen'] ['pen' 'laptop' 'chair']


In [44]:
print(np.intersect1d(a,b))

['laptop' 'pen']


In [45]:
print(np.union1d(a,b))

['book' 'chair' 'laptop' 'pen']


In [46]:
print(np.setdiff1d(a,b)) #elements in a that are not in b

['book']


In [47]:
print(np.in1d(a,b)) #which elements of a and also in b

[ True False  True]


# BROADCASTING

In [48]:
import numpy as np
start = np.zeros((2,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]]


In [49]:
add_rows = np.array([7,2,9])
print(add_rows)

[7 2 9]


In [50]:
y = start + add_rows
print(y)

[[7. 2. 9.]
 [7. 2. 9.]]


In [51]:
add_cols = np.array([[0,1]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]]


In [52]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]]


In [53]:
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]]


In [54]:
arrA = np.array([[25,36,69],[58,63,98],[87,63,74],[86,23,62]])
print(arrA)

[[25 36 69]
 [58 63 98]
 [87 63 74]
 [86 23 62]]


# SPEED TEST ndarray vs list

In [55]:
from numpy import arange
from timeit import Timer
size = 1000000
timeits = 1000

In [56]:
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [57]:
timer_numpy = Timer("nd_array.sum()","from__main__import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

SyntaxError: invalid syntax (<timeit-src>, line 1)

# a_list = list(arange(size))
print(type(a_list))

In [ ]:
timer_list = Timer("sum(a_list)","from__main__import a_list")
print("Time taken by list: %fseconds" %
      (timer_list.timeit(timeits)/timeits))

# TWitter Authentication

In [65]:
import twitter
import os
import pickle

In [72]:
if  not os.path.exists('secret_twitter_credentials.pkl'):
    Twitter={}
    Twitter['Consumer key'] = ''
    Twitter['Consumer Secret'] = ''
    Twitter['Access Token'] = ''
    Twitter['Access Token Secret'] = ''
    with open('secret_twitter_credentials.pkl','wb') as f:
        pickle.dump(Twitter, f)
else:
    Twitter=pickle.load(open('secret_twitter_credentials.pkl','rb'))

EOFError: Ran out of input

In [67]:
auth = twitter.oauth.OAuth(Twitter['Access Token'],
                           Twitter['Access Token Secret'],
                           Twitter['Consumer Key'],
                           Twitter['Consumer Secret'])

twitter_api = twitter.Twitter(auth = auth)

print(twitter_api)


KeyError: 'Consumer Key'